# Generated by Django 5.2 on 2025-04-27 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название курса', max_length=50, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью курса', null=True, upload_to='materials/preview', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Укажите описание курса', null=True, verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название урока', max_length=100, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, help_text='Укажите описание урока', null=True, verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью урока', null=True, upload_to='materials/preview', verbose_name='Превью')),
                ('link', models.URLField(blank=True, help_text='Добавьте ссылку на урок', null=True, verbose_name='Ссылка на урок')),
                ('courses', models.ForeignKey(blank=True, help_text='Укажите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='materials.lesson', verbose_name='Уроки'),
        ),
    ]
